name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: tools/set-tag-version
      - name: npm install
        run: |
          npm ci && npm run build && npm test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  # publish-gpr:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - name: npm install
  #       run: |
  #         npm config set //npm.pkg.github.com/:_authToken=${TOKEN}
  #         npm ci && npm run build && npm test
  #       env:
  #         TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: npm publish
  #       run: |
  #         echo "registry=https://npm.pkg.github.com/trustwallet" >> .npmrc
  #         npm publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
